# Generated by Django 2.1.15 on 2020-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
